### PR TITLE
debian: add dependencies that now need to be explicit

### PR DESCRIPTION
**Pull request by alfonsosanchezbeato**

### CODE REVIEW

**Review by sil2100 — APPROVED** [review]
Looks fine to me, but maybe Valentin could double-check.

**Review by valentindavid — APPROVED** [review]
Thank you

**Comment by valentindavid** [comment]
I suppose we need to make a core24 branch. And change the tests of the main branch to use 24.10.

**Comment by alfonsosanchezbeato** [comment]
Merging to `main` now. We'll have to work on running the tests on 24.10. I have also created a `core24` branch.

**Pull request merged**
